#trigger:
#- main

pool:
  vmImage: 'windows-latest'

variables:
  solution1: 'src/LogMessageGenerator.sln'
  solution2: 'src/Integration/Integration.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution1)'

- task: VSBuild@1
  inputs:
    solution: '$(solution1)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution2)'

- task: VSBuild@1
  inputs:
    solution: '$(solution2)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
